spring:
  application:
    name: configservergit

  cloud:
    config:
      server:
        git:

          default-label: main
#https://github:
#  com/Poorna-chandra2000/jobaapp-config-server:
#    git:
server:
  port: 8888

#eureka service ot needed for kubernetes deployment...kuberntes already has similar feature
#eureka:
#  client:
##    serviceUrl:
#    register-with-eureka: false
#    fetch-registry: false
