spring:
  application:
    name: configservergit

  cloud:
    config:
      server:
        git:
          uri: https://github.com/--config server repo link
          username: Poorna-chandra2000
          password: configserver password
          default-label: main

server:
  port: 8888

#eureka service ot needed for kubernetes deployment...kuberntes already has similar feature
#eureka:
#  client:
##    serviceUrl:
#    register-with-eureka: false
#    fetch-registry: false
